from pathlib import Path

DATA_DIR = Path(__file__).parent.parent / 'datasets'
INPUT_DIR = DATA_DIR / 'input'
OUTPUT_DIR = DATA_DIR / 'output'
COMPANY = INPUT_DIR / 'COMPANY_COMPANY.csv'
ENG_DESIGNATIONS = INPUT_DIR / 'SID_VSLENGINE_DESIGNATIONS.csv'
ENG_MODEL = INPUT_DIR / 'SID_VSLENGINE_MODELS.csv'
LR = INPUT_DIR / 'LR_ENGINE 20201016.csv'
VSL_ID = INPUT_DIR / 'SID_VESSELS.csv'
VSL_ENGINES = INPUT_DIR / 'SID_VSLENGINES.csv'
